### ISSUE TITLE
Cannot read property 'toString' of undefined SelectFilter example

### ISSUE THREAD

**Issue by jkratz55** [AllenFang/react-bootstrap-table#1057]
I am following the example almost identical and copied and the code for a table with a select filter but its not working.

I'm using ES6 and Bable. The product quality column does not display any data, and when the select changes I see an error in the console.

Uncaught TypeError: Cannot read property 'toString' of undefined
    at TableDataStore.filterText (http://localhost:8080/built/bundle.js:57638:29)
    at http://localhost:8080/built/bundle.js:57761:33
    at Array.filter (native)
    at TableDataStore._filter (http://localhost:8080/built/bundle.js:57677:35)
    at TableDataStore.filter (http://localhost:8080/built/bundle.js:57495:15)
    at BootstrapTable.__handleFilterData__REACT_HOT_LOADER__ (http://localhost:8080/built/bundle.js:27807:19)
    at BootstrapTable._this.handleFilterData (http://localhost:8080/built/bundle.js:26951:60)
    at Filter.<anonymous> (http://localhost:8080/built/bundle.js:27035:19)
    at Filter.EventEmitter.emit (http://localhost:8080/built/bundle.js:58524:18)
    at Filter.handleFilter (http://localhost:8080/built/bundle.js:58421:13)

import React from 'react';
        import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table';

        const products = [{
                id: 0,
                name: "Big Foot",
                quality: "bad"
            }, {
                id: 1,
                name: "Rubber Duck",
                quality: 'good'
            }
        ]

        const qualityType = {
            0: 'good',
            1: 'Bad',
            2: 'unknown'
        };

        function enumFormatter(cell, row, enumObject) {
            return enumObject[cell];
        }

        export default class SelectFilter extends React.Component {
            render() {

                console.log("RENDERING...")

                return (
                    <div>
                        <BootstrapTable data={ products }>
                        <TableHeaderColumn dataField='id' isKey>Product ID</TableHeaderColumn>
                        <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
                        <TableHeaderColumn dataField='quality' filterFormatted dataFormat={ enumFormatter } formatExtraData={ qualityType }
                                        filter={ { type: 'SelectFilter', options: qualityType } }>Product Quality</TableHeaderColumn>
                        </BootstrapTable>
                    </div>
                );
            }
        }

**Comment by jkratz55** [comment]
Nevermind I did something silly!
