### ISSUE TITLE
TypeError: Cannot add property clearSortCaret, object is not extensible

### ISSUE THREAD

**Issue by PavanRaj999** [AllenFang/react-bootstrap-table#1484]
And my code look like : 

import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table'
import React, { Component } from 'react'

export class TableComponent extends Component {

  constructor(props) {
    super(props)
    this.foo = 'Hello World!'
  }

  render() {
    let products = 'Hello'
    products = [{
      id: 1,
      name: 'Item name 1',
      price: 100,
    }, {
      id: 2,
      name: 'Item name 2',
      price: 100,
    },
    ]
    const isKeyProp = true
    return (
      <BootstrapTable data={products} striped={false} hover={false}>
        <TableHeaderColumn dataField="id" isKey={isKeyProp} dataAlign="center" dataSort={false}>Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField="name" dataSort={false}>Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField="price" >Product Price</TableHeaderColumn>
      </BootstrapTable>
    )
  }
}

export default TableComponent

**Comment by PavanRaj999** [comment]
Not able to render TableComponent at all : 
render.js:65 TypeError: Cannot add property clearSortCaret, object is not extensible
    at TableHeader.<anonymous> (http://localhost:6006/static/preview.bundle.js:67709:37)
    at Array.forEach (<anonymous>)
    at new TableHeader (http://localhost:6006/static/preview.bundle.js:67708:25)
    at http://localhost:6006/static/preview.bundle.js:32738:18
    at measureLifeCyclePerf (http://localhost:6006/static/preview.bundle.js:32518:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (http://localhost:6006/static/preview.bundle.js:32737:16)
    at ReactCompositeComponentWrapper._constructComponent (http://localhost:6006/static/preview.bundle.js:32723:21)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:6006/static/preview.bundle.js:32631:21)
    at Object.mountComponent (http://localhost:6006/static/preview.bundle.js:8182:35)
    at Object.obj.(anonymous function) [as mountComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8598:20)

**Comment by AllenFang** [comment]
@PavanRaj999 sorry I can't reproduce your issue, everything work well, any idea?

BTW, please make your example code readable....  could you please check your code again??? I think you cant understand your code   lol
