### ISSUE TITLE
Error when adding Search/Striped... Cannot call a class as a function

### ISSUE THREAD

**Issue by georgewritescode** [AllenFang/react-bootstrap-table#1515]
I am using version: 3.4.6 (the latest)

The table works beautifully when I don't add an option like search={true} or striped={true} but when I do I get this error:
```
Uncaught TypeError: Cannot call a class as a function
    at _classCallCheck (http://callerflow.app/js/dashboard.js:68768:99)
    at ToastContainer (http://callerflow.app/js/dashboard.js:68782:5)
    at http://callerflow.app/js/dashboard.js:129381:16
    at measureLifeCyclePerf (http://callerflow.app/js/dashboard.js:129150:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (http://callerflow.app/js/dashboard.js:129380:14)
    at ReactCompositeComponentWrapper._constructComponent
........Moar Stacktract
```

This is my code:
```
import React from 'react';
var ReactBsTable  = require('react-bootstrap-table');
var BootstrapTable = ReactBsTable.BootstrapTable;
var TableHeaderColumn = ReactBsTable.TableHeaderColumn;

var products = [{
      id: 1,
      name: "Product1",
      price: 120
  }, {
      id: 2,
      name: "Product2",
      price: 80
  }];


class TextHistoryTable extends React.Component {
    render() {
   
            return (
                <BootstrapTable search={true} data={ products }
                >
                    <TableHeaderColumn dataField='name' isKey={ true }>Col1</TableHeaderColumn>
                    <TableHeaderColumn dataField='price'>Col2</TableHeaderColumn>
                </BootstrapTable>);
    }
}

export default TextHistoryTable;
```

**Comment by crowdwave** [comment]
Try as follows, note that striped does not have ={true}

```
        <BootstrapTable data={this.state.data}
                        selectRow={selectRowProp}
                        options={options}
                        striped
                        hover
                        tableStyle={{'marginLeft': '0px', 'marginRight': '0px', 'paddingLeft': '0px', 'paddingRight': '0px'}}
                        ref="table">

```

**Comment by AllenFang** [comment]
Thanks @crowdwave's answer. I think this is not a issue, let me know if the problem still remains.

**Comment by georgewritescode** [comment]
Hi, the problem still remains with search. 
the striped attribute instead of striped={true} works but having search={true}
doesnt work and still produces the error: Uncaught TypeError: Cannot call a class as a function

**Comment by AllenFang** [comment]
@georgewritescode sorry, I still cant understand this issue, any simple and minimal repo for me to reproduce this problems? it will be very helpful. thanks

**Comment by crowdwave** [comment]
@georgewritescode - why are you trying to do it a different way when the working way is described above?
