### ISSUE TITLE
handleFilterData throws errors

### ISSUE THREAD

**Issue by danieltsai-ck** [AllenFang/react-bootstrap-table#976]
I recently upgraded the version of react-bootstrap-table from 2.5.9 to 2.9.1 and `this.refs.table.handleFilterData()` is now throwing errors.

```
Uncaught TypeError: Cannot read property 'cond' of undefined
    at http://localhost:3000/bundle.js:91550:86
    at Array.filter (native)
    at TableDataStore._filter (http://localhost:3000/bundle.js:91468:35)
    at TableDataStore.filter (http://localhost:3000/bundle.js:91288:15)
    at TableDataStore._refresh (http://localhost:3000/bundle.js:91153:44)
    at TableDataStore.setData (http://localhost:3000/bundle.js:91060:13)
    at BootstrapTable.componentWillReceiveProps (http://localhost:3000/bundle.js:81021:19)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:3000/bundle.js:15883:15)
    at ReactCompositeComponentWrapper.wrapper [as updateComponent] (http://localhost:3000/bundle.js:9763:22)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:3000/bundle.js:15830:11)
```

Was there a change to how `this.refs.table.handleFilterData()` should be called?  This is how I'm calling it when I was using version 2.5.9.

```
componentWillReceiveProps(nextProps) {
    this.refs.table.handleFilterData({ columnField: nextProps.filterValue });
    ...
},

render() {
    return (
        ...
        <BootstrapTable
            ref="table"
            ...
        >
            <TableHeaderColumn dataField="columnField">Column Field</TableHeaderColumn>
            ...
        </BootstrapTable>
    );
}
```

Thanks in advance for the help!

**Comment by AllenFang** [comment]
@danieltsai-ck, it's because the text filter now already support the `eq` and `like` for user, anyway, I'll fix it  as soon as possible. thanks

**Comment by AllenFang** [comment]
Fxed on `v2.9.2`, check this out.

**Comment by danieltsai-ck** [comment]
Thanks, everything seems to work now!
